name: Generate Site

on:
  push:
  pull_request:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 17
    - run: |
        mvn --no-transfer-progress package exec:java -Dexec.mainClass=org.javabubble.generator.SiteGenerator
      working-directory: generator

    # Publish to AWS Bucket
    - uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-central-1
      if: github.ref == 'refs/heads/main'
    - run: |
        aws s3 sync generator/target/site s3://javabubble.org
        aws cloudfront create-invalidation --distribution-id EH2BVKQRF4MDG --paths "/*"
      if: github.ref == 'refs/heads/main'
